SECTION_1_PROMPT = {'name': 'Company Profile & Strategic Alignment', 'prompt': 'You are an AI strategy evaluator for companies across industries. Analyze the following answers to assess how well the company aligns its business goals with AI strategy and executive leadership:\n\n{{responses}}\n\nEvaluate the following:\n- Strategic clarity of AI goals and mission alignment\n- Executive sponsorship and AI leadership structure\n- Formal AI strategy, roadmap, and investment approach\n- Integration of AI with business outcomes and objectives\n- Risk assessment and resistance management\n\nScore from 1 (no alignment) to 10 (fully embedded AI strategy). Return a score and a one-paragraph justification.'}

SECTION_2_PROMPT = {'name': 'AI Capabilities & Technical Maturity', 'prompt': 'You are a technical AI assessor. Given the responses below, score the company\'s AI/ML technical maturity:\n\n{{responses}}\n\nEvaluate:\n- Breadth and depth of AI capabilities (NLP, CV, GenAI, MLOps, etc.)\n- Internal talent, tools, and development frameworks\n- AI lifecycle practices (model management, data strategy, monitoring)\n- Use of open-source, proprietary, or specialized models\n- Personal AI tool usage and confidence levels\n- Business function integration and impact measurement\n\nScore from 1 (low maturity) to 10 (highly mature, modern stack). Provide a score and a short justification.'}

SECTION_3_GOVCON_PROMPT = {'name': 'Government AI Integration & Contract Performance', 'prompt': "You're an evaluator focused on federal AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Past performance delivering AI in government settings\n- Knowledge of government environments (IL4+, SCIF, JWICS)\n- Use of POCs or MVPs to demonstrate AI capabilities\n- Testing, explainability, compliance (T&E, ethics, etc.)\n- Security clearances and government partnerships\n- Alignment with government AI priorities\n\nScore from 1 (no relevant experience) to 10 (proven AI execution in federal programs). Return score and concise reasoning."}

SECTION_3_HEALTHCARE_PROMPT = {'name': 'AI Adoption & Compliance in Healthcare Settings', 'prompt': "You're an evaluator focused on healthcare AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Healthcare-specific AI capabilities and use cases\n- Compliance with healthcare regulations (HIPAA, FDA, ONC)\n- Clinical validation and real-world evidence practices\n- Integration with healthcare systems (EHRs, medical devices)\n- Partnerships with healthcare providers and institutions\n- Patient safety and ethical AI considerations\n\nScore from 1 (no healthcare AI experience) to 10 (proven AI execution in healthcare settings). Return score and concise reasoning."}

SECTION_3_FINANCE_PROMPT = {'name': 'AI Integration & Financial Services Delivery', 'prompt': "You're an evaluator focused on financial services AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Financial AI capabilities (fraud detection, credit scoring, trading)\n- Compliance with financial regulations (SEC, FINRA, GDPR, PCI DSS)\n- Model governance and risk management practices\n- Integration with financial workflows and systems\n- Partnerships with financial institutions\n- Real-time risk management and compliance monitoring\n\nScore from 1 (no financial AI experience) to 10 (proven AI execution in financial services). Return score and concise reasoning."}

SECTION_4_PROMPT = {'name': 'Partnerships, Ecosystem & Industry Engagement', 'prompt': "Evaluate this company's AI ecosystem engagement:\n\n{{responses}}\n\nFocus on:\n- Active partnerships (cloud, hardware, foundation model companies)\n- Academic or consortium participation\n- Industry-specific partnerships and collaborations\n- Ecosystem positioning and strategic relationships\n\nScore 1–10 based on strength, diversity, and strategic nature of partnerships. Include score and a 1-paragraph rationale."}

SECTION_5_PROMPT = {'name': 'AI Talent, Culture & Organizational Readiness', 'prompt': 'You\'re evaluating AI organizational readiness. Assess this company\'s internal posture:\n\n{{responses}}\n\nConsider:\n- Number and distribution of AI roles across functions\n- Hiring, upskilling, ethics and governance training\n- Internal AI usage (HR, marketing, BD, proposals, account planning)\n- Culture of adoption vs. pilot-only mentality\n- Business development and customer relationship AI integration\n\nGive a 1–10 score for talent and cultural AI readiness, and explain your reasoning.'}

SECTION_6_PROMPT = {'name': 'Future Readiness & Differentiators', 'prompt': "Assess the company's forward-looking AI posture:\n\n{{responses}}\n\nEvaluate:\n- Investment in advanced or emerging AI technologies\n- Unique differentiators in their target AI market\n- Ability to scale and overcome challenges\n- Clarity of 3–5 year vision in AI ecosystem\n- Workforce transformation strategy\n- Strategic initiatives and collaboration opportunities\n\nScore 1–10 based on innovation, strategic foresight, and defensibility. Provide score + justification."}

# Get-Well Plan Generation Prompts
GETWELL_SECTION_1_PROMPT = {'name': 'Company Profile & Strategic Alignment Get-Well Plan', 'prompt': 'You are an AI strategy consultant. Based on the assessment responses and score for Company Profile & Strategic Alignment, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\nCompany Type: {{company_type}}\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins and foundational improvements\n2. **Short-term Goals (3-6 months)**: Strategic initiatives and capability building\n3. **Long-term Vision (6-12 months)**: Transformational changes and advanced capabilities\n4. **Success Metrics**: How to measure progress and success\n5. **Resource Requirements**: Budget, personnel, and technology needs\n\nFocus on:\n- Strategic AI alignment and executive leadership\n- Formal AI strategy development\n- Investment approach and resource allocation\n- Risk management and resistance mitigation\n\nProvide actionable, specific recommendations tailored to the company type and current maturity level.'}

GETWELL_SECTION_2_PROMPT = {'name': 'AI Capabilities & Technical Maturity Get-Well Plan', 'prompt': 'You are an AI technical consultant. Based on the assessment responses and score for AI Capabilities & Technical Maturity, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\nCompany Type: {{company_type}}\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Technical quick wins and tool adoption\n2. **Short-term Goals (3-6 months)**: Capability building and process improvement\n3. **Long-term Vision (6-12 months)**: Advanced technical capabilities and innovation\n4. **Success Metrics**: Technical KPIs and performance indicators\n5. **Resource Requirements**: Technology, tools, and expertise needs\n\nFocus on:\n- AI/ML capability development and tooling\n- Technical talent acquisition and training\n- MLOps and lifecycle management\n- Data infrastructure and strategy\n- Personal AI tool adoption and confidence\n\nProvide specific, technical recommendations with implementation timelines and success criteria.'}

GETWELL_SECTION_3_GOVCON_PROMPT = {'name': 'Government AI Integration Get-Well Plan', 'prompt': 'You are a government contracting AI consultant. Based on the assessment responses and score for Government AI Integration & Contract Performance, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in government AI readiness\n2. **Short-term Goals (3-6 months)**: Contract performance and capability building\n3. **Long-term Vision (6-12 months)**: Advanced government AI capabilities\n4. **Success Metrics**: Contract wins, performance indicators, and compliance metrics\n5. **Resource Requirements**: Clearances, partnerships, and technology needs\n\nFocus on:\n- Government contract performance and delivery\n- Security clearances and compliance\n- Government partnerships and relationships\n- AI testing, evaluation, and accreditation\n- Go-to-market strategy for public sector\n\nProvide specific recommendations for government contracting success with AI capabilities.'}

GETWELL_SECTION_3_HEALTHCARE_PROMPT = {'name': 'Healthcare AI Adoption Get-Well Plan', 'prompt': 'You are a healthcare AI consultant. Based on the assessment responses and score for AI Adoption & Compliance in Healthcare Settings, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in healthcare AI compliance\n2. **Short-term Goals (3-6 months)**: Clinical validation and deployment\n3. **Long-term Vision (6-12 months)**: Advanced healthcare AI capabilities\n4. **Success Metrics**: Clinical outcomes, regulatory compliance, and adoption metrics\n5. **Resource Requirements**: Clinical expertise, regulatory knowledge, and technology needs\n\nFocus on:\n- Healthcare compliance (HIPAA, FDA, ONC)\n- Clinical validation and real-world evidence\n- Healthcare system integration (EHRs, medical devices)\n- Clinical partnerships and collaborations\n- Patient safety and ethical AI considerations\n\nProvide specific recommendations for healthcare AI success with regulatory compliance.'}

GETWELL_SECTION_3_FINANCE_PROMPT = {'name': 'Financial Services AI Integration Get-Well Plan', 'prompt': 'You are a financial services AI consultant. Based on the assessment responses and score for AI Integration & Financial Services Delivery, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in financial AI compliance\n2. **Short-term Goals (3-6 months)**: Financial AI deployment and integration\n3. **Long-term Vision (6-12 months)**: Advanced financial AI capabilities\n4. **Success Metrics**: Financial performance, compliance metrics, and risk reduction\n5. **Resource Requirements**: Regulatory expertise, financial partnerships, and technology needs\n\nFocus on:\n- Financial compliance (SEC, FINRA, GDPR, PCI DSS)\n- Model governance and risk management\n- Financial institution partnerships\n- Real-time risk management and compliance\n- Go-to-market strategy for financial services\n\nProvide specific recommendations for financial services AI success with regulatory compliance.'}

GETWELL_SECTION_4_PROMPT = {'name': 'Partnerships & Ecosystem Get-Well Plan', 'prompt': 'You are a business development AI consultant. Based on the assessment responses and score for Partnerships, Ecosystem & Industry Engagement, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\nCompany Type: {{company_type}}\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in partnership development\n2. **Short-term Goals (3-6 months)**: Strategic partnership building\n3. **Long-term Vision (6-12 months)**: Ecosystem leadership and innovation\n4. **Success Metrics**: Partnership value, collaboration outcomes, and market position\n5. **Resource Requirements**: Business development resources, partnership management, and ecosystem participation\n\nFocus on:\n- AI hardware and cloud partnerships\n- Academic and research collaborations\n- Industry consortium participation\n- Foundation model company relationships\n- Strategic ecosystem positioning\n\nProvide specific recommendations for building a strong AI ecosystem presence.'}

GETWELL_SECTION_5_PROMPT = {'name': 'AI Talent & Culture Get-Well Plan', 'prompt': 'You are an organizational AI consultant. Based on the assessment responses and score for AI Talent, Culture & Organizational Readiness, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\nCompany Type: {{company_type}}\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in talent and culture\n2. **Short-term Goals (3-6 months)**: Workforce development and cultural change\n3. **Long-term Vision (6-12 months)**: Advanced AI organizational capabilities\n4. **Success Metrics**: Talent metrics, cultural indicators, and organizational performance\n5. **Resource Requirements**: HR resources, training programs, and cultural initiatives\n\nFocus on:\n- AI talent acquisition and development\n- Organizational culture and AI adoption\n- Training and upskilling programs\n- Ethical AI guidelines and governance\n- Business development AI integration\n\nProvide specific recommendations for building AI-ready talent and culture.'}

GETWELL_SECTION_6_PROMPT = {'name': 'Future Readiness Get-Well Plan', 'prompt': 'You are a strategic AI consultant. Based on the assessment responses and score for Future Readiness & Differentiators, generate a comprehensive Get-Well Plan:\n\nAssessment Responses:\n{{responses}}\n\nCurrent Score: {{score}}/10\nCompany Type: {{company_type}}\n\nGenerate a detailed Get-Well Plan that includes:\n1. **Immediate Actions (0-3 months)**: Quick wins in future readiness\n2. **Short-term Goals (3-6 months)**: Strategic capability building\n3. **Long-term Vision (6-12 months)**: Market leadership and innovation\n4. **Success Metrics**: Innovation metrics, market position, and competitive advantage\n5. **Resource Requirements**: R&D investment, strategic partnerships, and innovation resources\n\nFocus on:\n- Emerging AI technology investment\n- Competitive advantage development\n- Market scaling and deployment\n- Strategic vision and positioning\n- Innovation and differentiation\n\nProvide specific recommendations for future AI market leadership.'}