SECTION_1_PROMPT = {'name': 'Company Profile & Strategic Alignment', 'prompt': 'You are an AI strategy evaluator for companies across industries. Analyze the following answers to assess how well the company aligns its business goals with AI strategy and executive leadership:\n\n{{responses}}\n\nEvaluate the following:\n- Strategic clarity of AI goals and mission alignment\n- Executive sponsorship and AI leadership structure\n- Formal AI strategy, roadmap, and investment approach\n- Integration of AI with business outcomes and objectives\n- Risk assessment and resistance management\n\nScore from 1 (no alignment) to 10 (fully embedded AI strategy). Return a score and a one-paragraph justification.'}

SECTION_2_PROMPT = {'name': 'AI Capabilities & Technical Maturity', 'prompt': 'You are a technical AI assessor. Given the responses below, score the company\'s AI/ML technical maturity:\n\n{{responses}}\n\nEvaluate:\n- Breadth and depth of AI capabilities (NLP, CV, GenAI, MLOps, etc.)\n- Internal talent, tools, and development frameworks\n- AI lifecycle practices (model management, data strategy, monitoring)\n- Use of open-source, proprietary, or specialized models\n- Personal AI tool usage and confidence levels\n- Business function integration and impact measurement\n\nScore from 1 (low maturity) to 10 (highly mature, modern stack). Provide a score and a short justification.'}

SECTION_3_GOVCON_PROMPT = {'name': 'Government AI Integration & Contract Performance', 'prompt': "You're an evaluator focused on federal AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Past performance delivering AI in government settings\n- Knowledge of government environments (IL4+, SCIF, JWICS)\n- Use of POCs or MVPs to demonstrate AI capabilities\n- Testing, explainability, compliance (T&E, ethics, etc.)\n- Security clearances and government partnerships\n- Alignment with government AI priorities\n\nScore from 1 (no relevant experience) to 10 (proven AI execution in federal programs). Return score and concise reasoning."}

SECTION_3_HEALTHCARE_PROMPT = {'name': 'AI Adoption & Compliance in Healthcare Settings', 'prompt': "You're an evaluator focused on healthcare AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Healthcare-specific AI capabilities and use cases\n- Compliance with healthcare regulations (HIPAA, FDA, ONC)\n- Clinical validation and real-world evidence practices\n- Integration with healthcare systems (EHRs, medical devices)\n- Partnerships with healthcare providers and institutions\n- Patient safety and ethical AI considerations\n\nScore from 1 (no healthcare AI experience) to 10 (proven AI execution in healthcare settings). Return score and concise reasoning."}

SECTION_3_FINANCE_PROMPT = {'name': 'AI Integration & Financial Services Delivery', 'prompt': "You're an evaluator focused on financial services AI deployment. Based on these answers:\n\n{{responses}}\n\nAssess:\n- Financial AI capabilities (fraud detection, credit scoring, trading)\n- Compliance with financial regulations (SEC, FINRA, GDPR, PCI DSS)\n- Model governance and risk management practices\n- Integration with financial workflows and systems\n- Partnerships with financial institutions\n- Real-time risk management and compliance monitoring\n\nScore from 1 (no financial AI experience) to 10 (proven AI execution in financial services). Return score and concise reasoning."}

SECTION_4_PROMPT = {'name': 'Partnerships, Ecosystem & Industry Engagement', 'prompt': "Evaluate this company's AI ecosystem engagement:\n\n{{responses}}\n\nFocus on:\n- Active partnerships (cloud, hardware, foundation model companies)\n- Academic or consortium participation\n- Industry-specific partnerships and collaborations\n- Ecosystem positioning and strategic relationships\n\nScore 1–10 based on strength, diversity, and strategic nature of partnerships. Include score and a 1-paragraph rationale."}

SECTION_5_PROMPT = {'name': 'AI Talent, Culture & Organizational Readiness', 'prompt': 'You\'re evaluating AI organizational readiness. Assess this company\'s internal posture:\n\n{{responses}}\n\nConsider:\n- Number and distribution of AI roles across functions\n- Hiring, upskilling, ethics and governance training\n- Internal AI usage (HR, marketing, BD, proposals, account planning)\n- Culture of adoption vs. pilot-only mentality\n- Business development and customer relationship AI integration\n\nGive a 1–10 score for talent and cultural AI readiness, and explain your reasoning.'}

SECTION_6_PROMPT = {'name': 'Future Readiness & Differentiators', 'prompt': "Assess the company's forward-looking AI posture:\n\n{{responses}}\n\nEvaluate:\n- Investment in advanced or emerging AI technologies\n- Unique differentiators in their target AI market\n- Ability to scale and overcome challenges\n- Clarity of 3–5 year vision in AI ecosystem\n- Workforce transformation strategy\n- Strategic initiatives and collaboration opportunities\n\nScore 1–10 based on innovation, strategic foresight, and defensibility. Provide score + justification."}